#生产环境配置
server:
  port: 80
springdoc:
  api-docs:
    enabled: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  mail:
    host: smtp.163.com
    username: 18989152637@163.com
    password: EUMJBGDXOGPXPDOO
  rabbitmq:
    addresses: 111.231.7.198
    username: root
    password: 20031213dmy
    virtual-host: /
  datasource:
    url: jdbc:mysql://111.231.7.198:3306/forum
    username: root
    password: 20031213dmy
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6379
      host: 111.231.7.198
      password: 20031213dmy
      database: 2
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 10
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
  minio:
    endpoint: 'http://111.231.7.198:9000'
    username: 'root'
    password: '20031213dmy''
  weather:
    key: 37bbdfd307da4b5ead3242193381a7bd
